import ApplyForm from "@/components/ApplyForm";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>USA RENTAL APT|APPLICATION</title>
        <meta name="description" content="Generated by usa rental apt" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1450px] mx-auto">
        <ApplyForm />
      </main>
    </>
  );
}
