import PaymentUpdate from "@/components/PaymentUpdate";
import connectMongo from "@/db";
import paymentModel from "@/db/model/paymentModel";
import Head from "next/head";
function Dashboard({ apidata }) {
  const data = apidata[0];
  return (
    <>
      <Head>
        <title>USA RENTAL APT|DASHBOARD</title>
        <meta name="description" content="Generated by usa rental apt" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PaymentUpdate payment={data} />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  await connectMongo();
  const res = await paymentModel.find();
  return {
    props: {
      apidata: JSON.parse(JSON.stringify(res)),
    },
  };
};

export default Dashboard;
