import Head from "next/head";

export default function Gallery() {
  return (
    <>
      <Head>
        <title>USA RENTAL APT|GALLERY</title>
        <meta name="description" content="Generated by usa rental apt" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-[60vh]">
        <div>
          <h1 className="font-semibold text-xl text-center mt-10 capitalize text-neel">
            gallery
          </h1>
        </div>
      </main>
    </>
  );
}
